const SUPABASE_URL = 'https://qasjwpsgnchwxidpfaai.supabase.co';
const SUPABASE_KEY = 'sb_publishable_RmQkPdQmjSMQh13L2T6-9w_XnCcSxw-';
const db = window.supabase?.createClient?.(SUPABASE_URL, SUPABASE_KEY);
const LEGACY = 'sakura_orders_v4', LOCAL = 'sakura_orders_local_v1';
let orders = [], editing = null, filter = '全部', session = null, localMode = false;
const $ = id => document.getElementById(id), money = n => '¥' + (Number(n) || 0).toFixed(2);
const statuses = ['全部', '待购买', '已购买', '日本运输', '已发国内', '已完成', '已取消'];
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
function calc(p, t, s, c, x, f) { const traffic = (p < 1e4 ? t : p < 2e4 ? t / 2 : 0) * s, total = p * s + p * s * f / 100 + traffic; return { customerTotal: total, profit: total - total * x / 100 - p * c - t * c }; }
function toDb(o) { return { user_id:session.user.id, client_order_id:o.id, order_date:o.date, status:o.status, product:o.product, customer:o.customer || '', price_jpy:o.priceJPY || 0, transport_jpy:o.transportJPY || 0, sell_rate:o.sellRate || 0, cost_rate:o.costRate || 0, xianyu_rate:o.xianyuRate || 0, service_rate:o.serviceRate || 0, remark:o.remark || '', customer_total:o.customerTotal || 0, profit:o.profit || 0, updated_at:new Date().toISOString() }; }
function fromDb(o) { return { id:o.client_order_id, date:o.order_date, status:o.status, product:o.product, customer:o.customer, priceJPY:+o.price_jpy, transportJPY:+o.transport_jpy, sellRate:+o.sell_rate, costRate:+o.cost_rate, xianyuRate:+o.xianyu_rate, serviceRate:+o.service_rate, remark:o.remark, customerTotal:+o.customer_total, profit:+o.profit }; }
function localLoad() { try { orders = JSON.parse(localStorage.getItem(LOCAL) || '[]'); } catch { orders = []; } render(); }
function localSave() { localStorage.setItem(LOCAL, JSON.stringify(orders)); }
async function refresh() { if (!db || !session) return localLoad(); const { data, error } = await db.from('orders').select('*').order('order_date', { ascending:false }); if (error) throw error; orders = (data || []).map(fromDb); render(); }
async function migrate() { if (!db || !session) return; let old = []; try { old = JSON.parse(localStorage.getItem(LEGACY) || '[]'); } catch {} if (!old.length) return; const { error } = await db.from('orders').upsert(old.map(toDb), { onConflict:'user_id,client_order_id' }); if (error) throw error; localStorage.removeItem(LEGACY); toast(`已迁移 ${old.length} 笔旧订单`); }
function renderFilters() { $('filters').innerHTML = statuses.map(s => `<button class="filter ${s === filter ? 'active' : ''}" data-f="${s}">${s}</button>`).join(''); document.querySelectorAll('[data-f]').forEach(b => b.onclick = () => { filter = b.dataset.f; renderFilters(); render(); }); }
function badge(s) { return `<span class="badge ${s === '已完成' ? 'done' : s === '已取消' ? 'cancel' : ['日本运输','已发国内'].includes(s) ? 'transit' : ''}">${esc(s)}</span>`; }
function render() { const q = ($('search')?.value || '').toLowerCase(), rows = orders.filter(o => (filter === '全部' || o.status === filter) && [o.id,o.product,o.customer].join(' ').toLowerCase().includes(q)); $('body').innerHTML = rows.map(o => `<tr><td><b>${esc(o.id)}</b><small>${esc(o.date)}</small></td><td><b>${esc(o.product)}</b><small>${esc(o.customer || '未填写客户')}</small></td><td>¥${(+o.priceJPY || 0).toLocaleString()}</td><td>${money(o.customerTotal)}</td><td class="profitCell">${money(o.profit)}</td><td>${badge(o.status)}</td><td><button class="dots" data-edit="${esc(o.id)}">•••</button></td></tr>`).join(''); $('empty').style.display = rows.length ? 'none' : 'block'; const valid = orders.filter(o => o.status !== '已取消'), done = orders.filter(o => o.status === '已完成').length; $('nOrders').textContent = orders.length; $('nDone').textContent = done; $('doneRate').textContent = `完成率 ${orders.length ? (done / orders.length * 100).toFixed(0) : 0}%`; $('revenue').textContent = money(valid.reduce((n,o) => n + o.customerTotal, 0)); $('profit').textContent = money(valid.reduce((n,o) => n + o.profit, 0)); document.querySelectorAll('[data-edit]').forEach(b => b.onclick = () => open(orders.find(o => o.id === b.dataset.edit))); }
function open(o) { editing = o?.id || null; $('modalTitle').textContent = o ? '编辑订单' : '新建订单'; $('remove').style.visibility = o ? 'visible' : 'hidden'; const d = { date:new Date().toISOString().slice(0,10), status:'待购买', priceJPY:1e4, transportJPY:0, sellRate:.045, costRate:.0438, xianyuRate:1.6, serviceRate:10 }; Object.keys(d).concat(['product','customer','remark']).forEach(id => $(id).value = o?.[id] ?? d[id] ?? ''); $('backdrop').classList.add('open'); }
function close() { $('backdrop').classList.remove('open'); editing = null; }
function toast(t) { $('toast').textContent = t; $('toast').classList.add('show'); setTimeout(() => $('toast').classList.remove('show'), 1800); }
function enterLocal() { localMode = true; session = null; $('auth').classList.add('hidden'); localLoad(); toast('已进入本地模式，数据保存在此设备'); }
if ($('authForm')) $('authForm').onsubmit = async e => { e.preventDefault(); if (!db) return $('authError').textContent = '云端服务暂时不可用，可先使用本地模式'; const { error } = await db.auth.signInWithPassword({ email:$('authEmail').value.trim(), password:$('authPassword').value }); $('authError').textContent = error?.message || ''; };
if ($('signup')) $('signup').onclick = async () => { const email = $('authEmail').value.trim(), password = $('authPassword').value; if (!db) return $('authError').textContent = '云端服务暂时不可用，可先使用本地模式'; if (!email || password.length < 6) return $('authError').textContent = '请输入邮箱和至少 6 位密码'; $('authError').textContent = '正在创建账号…'; const { data, error } = await db.auth.signUp({ email, password, options:{ emailRedirectTo:location.href.split('#')[0] } }); if (error) return $('authError').textContent = error.message; if (data?.session) { $('authError').textContent = '注册成功，正在进入云端 ERP…'; return; } $('authError').textContent = '注册已提交，但确认邮件由 Supabase 邮件服务发送。若收不到，请检查垃圾邮件；免费默认邮件只发送给项目团队成员，需要在 Supabase 配置 SMTP 或将此邮箱加入团队。'; };
if ($('guest')) $('guest').onclick = enterLocal;
$('new').onclick = () => open(); $('close').onclick = $('cancel').onclick = close; $('search').oninput = render;
$('orderForm').onsubmit = async e => { e.preventDefault(); const p = +$('priceJPY').value || 0, t = +$('transportJPY').value || 0, s = +$('sellRate').value || 0, c = +$('costRate').value || 0, x = +$('xianyuRate').value || 0, f = +$('serviceRate').value || 0, o = { id:editing || 'DG-' + Date.now().toString().slice(-8), date:$('date').value, status:$('status').value, product:$('product').value.trim(), customer:$('customer').value.trim(), priceJPY:p, transportJPY:t, sellRate:s, costRate:c, xianyuRate:x, serviceRate:f, remark:$('remark').value.trim(), ...calc(p,t,s,c,x,f) }; if (!o.product) return toast('请填写商品名称'); if (localMode || !session || !db) { const i = orders.findIndex(v => v.id === o.id); i < 0 ? orders.unshift(o) : orders[i] = o; localSave(); close(); render(); toast('已保存到本机'); return; } const { error } = await db.from('orders').upsert(toDb(o), { onConflict:'user_id,client_order_id' }); if (error) return toast('保存失败：' + error.message); close(); await refresh(); toast('已保存到云端'); };
$('remove').onclick = async () => { if (!editing || !confirm('确定删除这笔订单吗？')) return; if (localMode || !session || !db) { orders = orders.filter(o => o.id !== editing); localSave(); close(); render(); toast('已删除'); return; } const { error } = await db.from('orders').delete().eq('client_order_id', editing); if (error) return toast('删除失败'); close(); await refresh(); };
if (db) db.auth.onAuthStateChange((_e, s) => { session = s; $('auth').classList.toggle('hidden', !!s || localMode); if (s) refresh().catch(e => toast('云端加载失败：' + e.message)); });
(async () => { if (!db) return enterLocal(); const { data } = await db.auth.getSession(); session = data.session; $('auth').classList.toggle('hidden', !!session); if (session) { await migrate(); await refresh(); } })().catch(() => enterLocal());
renderFilters();
